DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
  ALTER TABLE `cdr` ADD COLUMN `did` varchar(50) NOT NULL DEFAULT ''; 

END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;
